name: mbsi_medspacy
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab
  - spacy=2.3
  - pip
  - seaborn
  - scikit-learn
  - gensim
  - pymysql
  - pandas
  - keras
  - ipywidgets
  - widgetsnbextension
  - pip:
    - pyrush
    - medspacy
    - https://github.com/abchapman93/spacy_models/raw/master/releases/en_info_3700_i2b2_2012-0.1.0/dist/en_info_3700_i2b2_2012-0.1.0.tar.gz
